# Generated by Django 2.2.7 on 2019-11-20 18:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_expiry',
            field=models.DateField(default=datetime.datetime(2019, 12, 20, 18, 28, 52, 244997, tzinfo=utc)),
        ),
    ]
