# Generated by Django 2.2.7 on 2019-11-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20191120_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_expiry',
        ),
    ]
