# Generated by Django 2.2.7 on 2019-11-20 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_remove_subscription_subscription_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user_membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='subscription.UserMembership'),
        ),
    ]
