# Generated by Django 2.2.7 on 2019-11-22 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_auto_20191123_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 23, 2, 9, 28, 654890), verbose_name='ended_at'),
        ),
    ]
