# Generated by Django 2.2.7 on 2019-11-23 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_auto_20191123_0209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='usermembership',
            options={'verbose_name': 'User Membership', 'verbose_name_plural': 'User Memberships'},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 23, 12, 13, 0, 824505), verbose_name='ended_at'),
        ),
    ]
