# Generated by Django 2.2.7 on 2019-11-24 14:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_auto_20191123_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='interval',
            field=models.CharField(choices=[('Monthly', 'month'), ('Yearly', 'yearly')], default='Monthly', max_length=30, verbose_name='Plan Period'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 24, 19, 12, 23, 85112), verbose_name='billing_date'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.Membership', verbose_name='Plan list'),
        ),
    ]
